services:
  mysql:
    image: mysql:8.0
    container_name: bibliocore_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bibliocore
      MYSQL_USER: bibliocore_admin
      MYSQL_PASSWORD: abc123..
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bibliocore_pma
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"

volumes:
  mysql_data: